"""Typed integration boundaries; provider SDKs must stay behind these protocols."""

from collections.abc import Sequence
from typing import Protocol

from .models import Message, Passage


class Embedder(Protocol):
    def embed(self, texts: Sequence[str]) -> list[list[float]]: ...


class VectorStore(Protocol):
    def upsert(self, passages: Sequence[Passage], vectors: Sequence[Sequence[float]]) -> None: ...
    def query(self, vector: Sequence[float], limit: int) -> list[Passage]: ...
    def delete_document(self, document_id: str) -> None: ...


class ChatModel(Protocol):
    def rewrite(self, *, model: str, question: str, history: Sequence[Message]) -> str: ...
    def complete(self, *, model: str, question: str, passages: Sequence[Passage]) -> str: ...


class ConversationStore(Protocol):
    def create(self, model: str) -> str: ...
    def add_message(self, conversation_id: str, role: str, content: str) -> Message: ...
    def history(self, conversation_id: str, limit: int = 20) -> list[Message]: ...
